03-lection1/01-button
js-tasks-ru/htmlcss-20210610_aleksandra53 pull request #2
Opened 2021-06-16 21:31 UTC by NoaJinko

added button styles, fixed --blue variable according specification

2021-06-16 21:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-17 08:13 UTC, GSemikozov requested changes

2021-06-17 08:13 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 200px;
ширину лучше так жестко не фиксировать, наоборот, чтобы она была универсальной, пусть ширина определяется внутренним содержимым (зададим display: inline-block и уберем width). А если нужно будет растянуть по родителю - создадим модификатор `.button_full_width { width: 100%; }`

2021-06-17 08:13 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 15px;
высота кнопки соответствует тому как это определено в макете?) и - тут еще надо проверить box-sizing)

2021-06-17 08:13 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: default;
pointer-events: none; ставит курсор в default, так что пожалуй не обязательно указывать явно

2021-06-17 11:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-17 11:41 UTC, NoaJinko commented on 03-lection1/01-button/button.css
> +  width: 200px;
Готово. Модификатор создала, но в тестовой странице не применяла.

2021-06-17 11:41 UTC, NoaJinko commented on 03-lection1/01-button/button.css
> +  padding: 15px;
Ох уж этот пиксель :)

2021-06-17 11:42 UTC, NoaJinko commented on 03-lection1/01-button/button.css
> +  cursor: default;
Спасибо, и правда :)

2021-06-17 12:23 UTC, GSemikozov approved these changes

2021-06-17 12:24 UTC, merged